name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create local.properties
      run: |
        echo "ad.appid=\"${{ secrets.AD_APP_ID || 'ca-app-pub-3940256099942544~3347511713' }}\"" > local.properties
        echo "ad.home.banner=\"${{ secrets.AD_HOME_BANNER || 'ca-app-pub-3940256099942544/6300978111' }}\"" >> local.properties

    - name: Create google-services.json
      run: |
        cat <<EOT > app/google-services.json
        {
          "project_info": {
            "project_number": "000000000000",
            "project_id": "mock-project-id",
            "storage_bucket": "mock-project-id.appspot.com"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:000000000000:android:0000000000000000",
                "android_client_info": {
                  "package_name": "zechs.drive.stream"
                }
              },
              "oauth_client": [],
              "api_key": [
                {
                  "current_key": "mock-api-key"
                }
              ],
              "services": {
                "analytics_service": {
                  "status": 1
                },
                "appinvite_service": {
                  "status": 1,
                  "other_platform_oauth_client": []
                },
                "ads_service": {
                  "status": 2
                }
              }
            }
          ],
          "configuration_version": "1"
        }
        EOT

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
